# Generated by Django 4.2.9 on 2024-01-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agecode', '0002_eventattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='event_images/'),
        ),
    ]
