# Generated by Django 4.2.9 on 2024-01-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agecode', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_capacity',
            field=models.IntegerField(default=0, verbose_name='Capacity'),
        ),
    ]
