# Generated by Django 4.2.9 on 2024-01-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agecode', '0008_remove_event_spots_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='spots_remaining',
            field=models.IntegerField(default=0, verbose_name='Spots Remaining'),
        ),
    ]
